---
- name: Instala xcode command line developer tools
  shell: xcode-select --install || true
  register: xcode_result
  changed_when: "'already installed' not in xcode_result.stderr"

- name: Instala diversos programas com brew
  homebrew: name={{item}} state=present
  with_items:
    - adr-tools
    - chruby
    - diff-so-fancy
    - git
    - github-markdown-toc
    - jq
    - jump
    - macvim
    - pyenv
    - ruby-install
    - tree
    - vim
    - zsh
    - zsh-completions

- name: Instala diversos programas com cask
  homebrew_cask: name={{item}} state=present
  with_items:
    - 1password
    - appcleaner
    - docker
    - dropbox
    - evernote
    - firefox
    - gas-mask
    - google-drive-file-stream
    - gpg-suite
    - iterm2
    - java
    - jetbrains-toolbox
    - keepassx
    - macdown
    - qlmarkdown
    - qlstephen
    - slack
    - telegram
    - visual-studio-code
    - whatsapp

- name: Restaura o estilo do MacDown
  copy: src=Clearness-TW.css dest="~/Library/Application Support/MacDown/Styles/Clearness-TW.css"

- name: Configura o MacDown
  osx_defaults:
    domain: com.uranusjr.macdown
    key: "{{ item.chave }}"
    type: "{{ item.tipo }}"
    value: "{{ item.valor }}"
  with_items:
    - "{{ macdown_defaults }}"
