---
- hosts: localhost
  tasks:
  - name: Instala xcode command line developer tools
    shell: xcode-select --install || true
    register: xcode_result
    changed_when: "'already installed' not in xcode_result.stderr"
  - name: Instala diversos programas com brew
    homebrew: name={{item}}
    with_items:
      - chruby
      - git
      - jq
      - jump
      - pyenv
      - zsh
      - zsh-completions
  - name: Instala diversos programas com cask
    homebrew_cask: name={{item}}
    with_items:
      - 1password
      - appcleaner
      - docker
      - dropbox
      - gimp
      - google-drive-file-stream
      - gpgtools
      - iterm2
      - keepassx
      - macdown
      - qlmarkdown
      - qlstephen
      - slack
      - telegram
      - whatsapp
  - name: Instala Oh-my-zsh
    shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    register: ohmyzsh_result
    changed_when: "'You already have Oh My Zsh installed' not in ohmyzsh_result.stdout"
  - name: Instala jenv
    shell: sh -c "$(curl -L -s get.jenv.io)"
    register: jenv_result
    changed_when: "'You already have JENV installed' not in jenv_result.stdout"
  - name: Clona git-tdd
    git:
      repo: 'git@github.com:binkley/shell.git'
      dest: ~/workspaces/git/github/binkley/shell
  - name: Adiciona git-tdd no PATH
    file:
      src: '~/workspaces/git/github/binkley/shell/git/git-tdd'
      dest: '~/.bin/git-tdd'
      state: link
  - name: Clona adr-tools
    git:
      repo: 'git@github.com:npryce/adr-tools.git'
      dest: ~/workspaces/git/github/npryce/adr-tools
  - name: Adiciona script que limpa fotos de quadro branco
    file: src=./scripts/whiteboard-cleanq dest=~/.bin/whiteboard-clean
  - name: Configura zsh
    copy: src=./config_files/zshrc dest=~/.zshrc
          backup=true
  - name: Configura git
    copy: src=./config_files/git dest=~/.gitconfig
  - name: Configura ssh
    copy: src={{item}} dest=~/.ssh/
    with_fileglob:
      - ./config_files/ssh/*
  - name: Cria workspace
    file: path=~/workspace/{{item}} recurse=true state=directory
    with_items:
      - git/github/pedromanoel
      - git/bitbucket/pedromanoel
      - git/gitlab.com/pedromanoel
      - git/git.thoughtworks.net/pevange
      - git/local
