---
- hosts: localhost
  vars_files:
    - config_files/macdown.yml
  tasks:
  - import_tasks: tasks_programas.yml
    tags: [programas]
  - import_tasks: tasks_diretorios.yml
    tags: [diretorios]
  - import_tasks: tasks_configs.yml
    tags: [configs]

  - name: Configura o MacDown
    osx_defaults:
      domain: com.uranusjr.macdown
      key: "{{ item.chave }}"
      type: "{{ item.tipo }}"
      value: "{{ item.valor }}"
    with_items:
      - "{{ macdown_defaults }}"

  - name: Instala Oh-my-zsh
    shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    register: ohmyzsh_result
    changed_when: "'You already have Oh My Zsh installed' not in ohmyzsh_result.stdout"

  - name: Instala jenv
    shell: sh -c "$(curl -L -s get.jenv.io)"
    register: jenv_result
    changed_when: "'You already have JENV installed' not in jenv_result.stdout"

  - name: Clona git-tdd
    git:
      repo: 'git@github.com:binkley/shell.git'
      dest: ~/workspace/git/github/binkley/shell

  - name: Adiciona git-tdd no PATH
    file:
      src: '~/workspace/git/github/binkley/shell/git/git-tdd'
      dest: '~/.bin/git-tdd'
      state: link

  - name: Adiciona script que limpa fotos de quadro branco
    copy: src=./scripts/whiteboard-clean dest=~/.bin/whiteboard-clean

