---
- hosts: localhost
  tasks:
  - name: Instala diversos programas programas com brew
    homebrew: name={{item}}
    with_items:
      - git
      - pyenv
      - chruby
  - name: Instala diversos programas com cask
    homebrew_cask: name={{item}}
    with_items:
      - macdown
      - qlmarkdown
      - qlstephen
      - docker
      - appcleaner
