---
- hosts: localhost
  tasks:
  - name: Instala xcode command line developer tools
    shell: xcode-select --install || true
    register: xcode_result
    changed_when: "'already installed' not in xcode_result.stderr"
  - name: Instala diversos programas com brew
    homebrew: name={{item}}
    with_items:
      - chruby
      - git
      - jq
      - jump
      - pyenv
      - zsh
      - zsh-completions
  - name: Instala diversos programas com cask
    homebrew_cask: name={{item}}
    with_items:
      - appcleaner
      - docker
      - iterm2
      - macdown
      - qlmarkdown
      - qlstephen
  - name: Instala Oh-my-zsh
    shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    register: ohmyzsh_result
    changed_when: "'installed' not in ohmyzsh_result.stdout"
  - name: Configura zsh
    copy: src=./config_files/zshrc dest=~/.zshrc
          backup=true
  - name: Configura git
    copy: src=./config_files/git dest=~/.gitconfig
  - name: Configura ssh
    copy: src={{item}} dest=~/.ssh/
    with_fileglob:
      - ./config_files/ssh/*
