---
- name: Restaura configurações do zsh
  copy: src=./config_files/zshrc dest=~/.zshrc
        backup=true

- name: Restaura configurações do git
  copy: src=./config_files/git dest=~/.gitconfig

- name: Restaura configurações de ssh
  copy: src={{item}} dest=~/.ssh/ mode=0600
  with_fileglob:
    - ./config_files/ssh/*

- name: Restaura o estilo do MacDown
  copy: src=./config_files/Clearness-TW.css dest="~/Library/Application Support/MacDown/Styles/Clearness-TW.css"

