---
- name: Instala jenv
  homebrew:
    name: jenv

- name: Clona o repositório do git-tdd
  git:
    repo: 'git@github.com:binkley/shell.git'
    dest: ~/workspace/git/github/binkley/shell
    depth: 1

- name: Adiciona git-tdd no PATH
  file:
    src: '~/workspace/git/github/binkley/shell/git/git-tdd'
    dest: '/usr/local/bin/git-tdd'
    state: link

- name: Adiciona script que limpa fotos de quadro branco
  copy: src=whiteboard-clean dest=/usr/local/bin/ mode=0744

