---
- name: Restaura configurações do zsh
  copy: src=zshrc dest=~/.zshrc

- name: Restaura configurações do git
  copy: src=gitconfig dest=~/.gitconfig

- name: Instala Oh-my-zsh
  command: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  args:
    creates: ~/.oh-my-zsh/

- name: Restaura customizações do Oh-my-zsh
  copy: src=themes dest=~/.oh-my-zsh/custom/
