---
- name: Restaura configurações do zsh
  copy: src=zshrc dest=~/.zshrc

- name: Restaura configurações do git
  copy: src=gitconfig dest=~/.gitconfig

- name: Instala Oh-my-zsh
  command: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  args:
    creates: ~/.oh-my-zsh/

- name: Restaura customizações do Oh-my-zsh
  copy: src=themes dest=~/.oh-my-zsh/custom/

- name: Cria diretório de configuração do nvm
  file:
    path: ~/.nvm
    state: directory

- name: Baixa fontes do Powerline
  git:
    repo: https://github.com/powerline/fonts.git
    dest: ~/workspace/git/github/powerline/fonts
    depth: 1

- name: Instala fontes do Powerline
  command: ~/workspace/git/github/powerline/fonts/install.sh
  args:
    creates: ~/Library/Fonts/3270Medium.ttf
